const alumniData = [
    {
      id: 1,
      name: 'Ishmeet Singh Bhatia',
      title: 'System Engineer',
      company: 'Tata Consultancy Services',
      image: 'https://via.placeholder.com/150',
      following: true,
      followers: 500,
      likes: 1000,
    },
    {
      id: 2,
      name: 'Parth Soni',
      title: 'Java Developer',
      company: 'N/A',
      image: 'https://via.placeholder.com/150',
      following: false,
      followers: 200,
      likes: 500,
    },
    {
      id: 3,
      name: 'Yash Kumar Dhurve',
      title: 'Java Developer',
      company: 'N/A',
      image: 'https://via.placeholder.com/150',
      following: false,
      followers: 150,
      likes: 400,
    },
    {
      id: 4,
      name: 'Ankit Dhuware',
      title: 'Software Engineer',
      company: 'Google',
      image: 'https://via.placeholder.com/150',
      following: true,
      followers: 1000,
      likes: 2000,
    },
    {
      id: 5,
      name: 'Kuldeep Singh',
      title: 'Data Scientist',
      company: 'Microsoft',
      image: 'https://via.placeholder.com/150',
      following: true,
      followers: 800,
      likes: 1500,
    },
    {
      id: 6,
      name: 'Mradul Kumar Pandit',
      title: 'Product Manager',
      company: 'Amazon',
      image: 'https://via.placeholder.com/150',
      following: false,
      followers: 300,
      likes: 700,
    },
    {
      id: 7,
      name: 'Kaustubh Pandey',
      title: 'Full Stack Developer',
      company: 'Facebook',
      image: 'https://via.placeholder.com/150',
      following: false,
      followers: 250,
      likes: 600,
    },
    {
      id: 8,
      name: 'Rict',
      title: 'DevOps Engineer',
      company: 'IBM',
      image: 'https://via.placeholder.com/150',
      following: true,
      followers: 700,
      likes: 1200,
    },
    {
      id: 9,
      name: 'Krishnakant Dwivedi',
      title: 'Machine Learning Engineer',
      company: 'N/A',
      image: 'https://via.placeholder.com/150',
      following: false,
      followers: 180,
      likes: 350,
    },
  ];
  
  export default alumniData;